export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';

export const LOAD_FOCUS_BEGIN = 'LOAD_FOCUS_BEGIN';

export const LOAD_FOCUS_SUCCESS = 'LOAD_FOCUS_SUCCESS';

export const LOAD_FOCUS_FAIL = 'LOAD_FOCUS_FAIL';

export const UPDATE_SEARCH = 'UPDATE_SEARCH';

export const UPDATE_SORT = 'UPDATE_SORT';

export const WIPE_MESSAGE = 'WIPE_MESSAGE';

export const UPDATE_NAV = 'UPDATE_NAV';

export const LOAD_DATA_BEGIN = 'LOAD_DATA_BEGIN';

export const LOAD_DATA_SUCCESS = 'LOAD_DATA_SUCCESS';

export const LOAD_DATA_FAIL = 'LOAD_DATA_FAIL';

export const CREATE_TODO_FAIL = 'CREATE_TODO_FAIL';

export const CREATE_TODO_SUCCESS = 'CREATE_TODO_SUCCESS';

export const UPDATE_TODO_FAIL = 'UPDATE_TODO_FAIL';

export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS';

export const DELETE_TODO_FAIL = 'DELETE_TODO_FAIL';

export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
